# =============================================================================
# VPS Proxy Stack for Docker Swarm
# =============================================================================
# Traefik reverse proxy handling all ingress traffic.
# Provides TLS termination, routing, and load balancing.
#
# Networks:
#   - vps-public: External overlay network shared with services
#
# Deploy:
#   ACME_EMAIL=you@example.com docker stack deploy -c services/proxy-stack.yml proxy
# =============================================================================

services:
  traefik:
    image: traefik:v3.6
    networks:
      - vps-public
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    command:
      # API (dashboard not exposed publicly)
      - "--api.dashboard=true"
      - "--api.insecure=false"

      # Docker Swarm provider
      - "--providers.swarm=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.network=vps-public"

      # Dynamic config (file provider)
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"

      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"

      # Let's Encrypt (TLS-ALPN challenge)
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:?set ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.caserver=${ACME_CA_SERVER:-https://acme-v02.api.letsencrypt.org/directory}"

      # Logging
      - "--log.level=${TRAEFIK_LOG_LEVEL:-INFO}"
      - "--accesslog=true"

      # Health check
      - "--ping=true"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/letsencrypt
      - /mnt/data/traefik-dynamic:/etc/traefik/dynamic:ro

    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 3s
      retries: 3

networks:
  vps-public:
    external: true

volumes:
  traefik-certificates:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/traefik-certificates
