# =============================================================================
# MERGED VPS Services Stack for Docker Swarm (Traefik)
# =============================================================================
# Fresh start: single stack hosting Traefik + PostgreSQL + n8n + Postiz + Redis.
# Domains:
#   - https://n8n.vps.andrejvysny.sk
#   - https://postiz.vps.andrejvysny.sk
#
# Deploy:
#   docker stack deploy -c services/services-stack.yml services-stack
#
# Notes:
# - PostgreSQL is a single shared instance (postgres:17-alpine) with two DBs:
#     - n8n (user: n8n)
#     - postiz (user: postiz)
# - Passwords are currently inline for simplicity; we can migrate to Swarm secrets.
# =============================================================================

services:
  traefik:
    image: traefik:v3.6
    networks:
      - vps-public
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"

      - "--providers.swarm=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.network=vps-public"

      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"

      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:?set ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.caserver=${ACME_CA_SERVER:-https://acme-v02.api.letsencrypt.org/directory}"

      - "--log.level=${TRAEFIK_LOG_LEVEL:-INFO}"
      - "--accesslog=true"
      - "--ping=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/letsencrypt
      - /mnt/data/traefik-dynamic:/etc/traefik/dynamic:ro
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 3s
      retries: 3

  postgres:
    image: postgres:17-alpine
    networks:
      - db-internal
    environment:
      # Superuser (used only for bootstrap/admin)
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${POSTGRES_SUPERUSER_PASSWORD:?set POSTGRES_SUPERUSER_PASSWORD}"
      # Default DB created by image (we'll create our own DBs via init script)
      POSTGRES_DB: "postgres"
      # Pass DB passwords to init script
      N8N_DB_PASSWORD: "${N8N_DB_PASSWORD:?set N8N_DB_PASSWORD}"
      POSTIZ_DB_PASSWORD: "${POSTIZ_DB_PASSWORD:?set POSTIZ_DB_PASSWORD}"
      TEMPORAL_DB_PASSWORD: "${TEMPORAL_DB_PASSWORD:-${POSTIZ_DB_PASSWORD}}"
    configs:
      - source: pg-init
        target: /docker-entrypoint-initdb.d/01-init.sh
        mode: 0555
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 3s
      retries: 10

  postiz-redis:
    image: redis:7.2
    networks:
      - postiz-internal
    volumes:
      - postiz-redis-data:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10

  postiz-temporal:
    image: temporalio/server:latest
    networks:
      - postiz-internal
    environment:
      DB: "postgresql"
      DB_PORT: "5432"
      DB_USER: "temporal"
      DB_PASSWORD: "${TEMPORAL_DB_PASSWORD:?set TEMPORAL_DB_PASSWORD}"
      DB_SOURCE: "postgresql://temporal:${TEMPORAL_DB_PASSWORD}@services-stack_postgres:5432/temporal?sslmode=disable"
      SERVICES_FRONTEND_ADDRESS: "services-stack_postiz-temporal:7233"
      UI_ENABLED: "true"
    depends_on:
      - postiz
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: ["temporal-server", "start-dev"]
    healthcheck:
      test: ["CMD", "tctl", "cluster", "health"]
      interval: 30s
      timeout: 10s
      retries: 5

  postiz-temporal-ui:
    image: temporalio/ui:latest
    networks:
      - postiz-internal
    environment:
      TEMPORAL_ADDRESS: "services-stack_postiz-temporal:7233"
      TEMPORAL_ENVIRONMENT: "development"
    depends_on:
      - postiz-temporal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.temporal.rule=Host(`temporal.vps.andrejvysny.sk`)"
      - "traefik.http.routers.temporal.entrypoints=websecure"
      - "traefik.http.routers.temporal.tls=true"
      - "traefik.http.routers.temporal.tls.certresolver=letsencrypt"
      - "traefik.http.services.temporal.loadbalancer.server.port=8080"

  postiz:
    image: ghcr.io/gitroomhq/postiz-app:latest
    networks:
      - vps-public
      - postiz-internal
      - db-internal
    environment:
      MAIN_URL: "https://postiz.vps.andrejvysny.sk"
      FRONTEND_URL: "https://postiz.vps.andrejvysny.sk"
      NEXT_PUBLIC_BACKEND_URL: "https://postiz.vps.andrejvysny.sk/api"
      JWT_SECRET: "${POSTIZ_JWT_SECRET:?set POSTIZ_JWT_SECRET}"

      # Shared Postgres
      DATABASE_URL: "postgresql://postiz:${POSTIZ_DB_PASSWORD}@services-stack_postgres:5432/postiz"

      REDIS_URL: "redis://services-stack_postiz-redis:6379"
      BACKEND_INTERNAL_URL: "http://localhost:3000"

      # Temporal connection
      TEMPORAL_ADDRESS: "services-stack_postiz-temporal:7233"

      IS_GENERAL: "true"
      DISABLE_REGISTRATION: "false"
      RUN_CRON: "true"

      STORAGE_PROVIDER: "local"
      UPLOAD_DIRECTORY: "/uploads"
      NEXT_PUBLIC_UPLOAD_DIRECTORY: "/uploads"
    volumes:
      - postiz-config:/config/
      - postiz-uploads:/uploads/
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.postiz.rule=Host(`postiz.vps.andrejvysny.sk`)"
        - "traefik.http.routers.postiz.entrypoints=websecure"
        - "traefik.http.routers.postiz.tls=true"
        - "traefik.http.routers.postiz.tls.certresolver=letsencrypt"
        - "traefik.http.services.postiz.loadbalancer.server.port=5000"

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    networks:
      - vps-public
      - db-internal
    environment:
      # Database
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: services-stack_postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: "${N8N_DB_PASSWORD:?set N8N_DB_PASSWORD}"

      # Public URL (important for webhooks)
      N8N_HOST: n8n.vps.andrejvysny.sk
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      WEBHOOK_URL: https://n8n.vps.andrejvysny.sk/

      NODE_ENV: production
      GENERIC_TIMEZONE: Europe/Bratislava

      # Strongly recommended for n8n (keeps credentials stable)
      N8N_ENCRYPTION_KEY: "${N8N_ENCRYPTION_KEY:?set N8N_ENCRYPTION_KEY}"
    volumes:
      - n8n-data:/home/node/.n8n
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.n8n.rule=Host(`n8n.vps.andrejvysny.sk`)"
        - "traefik.http.routers.n8n.entrypoints=websecure"
        - "traefik.http.routers.n8n.tls=true"
        - "traefik.http.routers.n8n.tls.certresolver=letsencrypt"
        - "traefik.http.services.n8n.loadbalancer.server.port=5678"

networks:
  vps-public:
    external: true
  db-internal:
    driver: overlay
  postiz-internal:
    driver: overlay

configs:
  pg-init:
    file: ./pg-init.sh

volumes:
  traefik-certificates:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/traefik-certificates

  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/postgres/pg

  n8n-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/n8n/files

  postiz-redis-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/postiz/redis

  postiz-uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/postiz/uploads

  postiz-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/postiz/config
