# =============================================================================
# MERGED VPS Services Stack for Docker Swarm (Traefik)
# =============================================================================
# Single stack hosting Traefik + PostgreSQL + n8n + Postiz + Redis.
# Domains:
#   - https://n8n.vps.andrejvysny.sk
#   - https://postiz.vps.andrejvysny.sk
#
# Deploy:
#   docker stack deploy -c services/services-stack.yml services-stack
# =============================================================================

services:
  traefik:
    image: traefik:v3.6
    networks:
      - vps-public
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"

      - "--providers.swarm=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.network=vps-public"

      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"

      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:?set ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.caserver=${ACME_CA_SERVER:-https://acme-v02.api.letsencrypt.org/directory}"

      - "--log.level=${TRAEFIK_LOG_LEVEL:-INFO}"
      - "--accesslog=true"
      - "--ping=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/letsencrypt
      - /mnt/data/traefik-dynamic:/etc/traefik/dynamic:ro
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 3s
      retries: 3

  postgres:
    image: postgres:17-alpine
    networks:
      - db-internal
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${POSTGRES_SUPERUSER_PASSWORD}"
      POSTGRES_DB: "postgres"
    configs:
      - source: pg-init-v2
        target: /docker-entrypoint-initdb.d/01-init.sql
        mode: 0444
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 3s
      retries: 10

  postiz-redis:
    image: redis:7.2
    networks:
      - postiz-internal
    volumes:
      - postiz-redis-data:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10

  temporal-elasticsearch:
    image: elasticsearch:7.17.27
    networks:
      - temporal-internal
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=512mb
      - cluster.routing.allocation.disk.watermark.high=256mb
      - cluster.routing.allocation.disk.watermark.flood_stage=128mb
    volumes:
      - temporal-es-data:/usr/share/elasticsearch/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  temporal:
    image: temporalio/auto-setup:1.28.1
    networks:
      - db-internal
      - temporal-internal
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=${TEMPORAL_DB_PASSWORD}
      - POSTGRES_SEEDS=services-stack_postgres

      - ENABLE_ES=true
      - ES_SEEDS=services-stack_temporal-elasticsearch
      - ES_VERSION=v7
      - TEMPORAL_NAMESPACE=default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    # healthcheck omitted (image may not include tctl)

  postiz:
    image: ghcr.io/gitroomhq/postiz-app:latest
    networks:
      - vps-public
      - postiz-internal
      - db-internal
    environment:
      MAIN_URL: "https://postiz.vps.andrejvysny.sk"
      FRONTEND_URL: "https://postiz.vps.andrejvysny.sk"
      NEXT_PUBLIC_BACKEND_URL: "https://postiz.vps.andrejvysny.sk/api"
      JWT_SECRET: "${POSTIZ_JWT_SECRET}"

      DATABASE_URL: "postgresql://postiz:${POSTIZ_DB_PASSWORD}@services-stack_postgres:5432/postiz"
      REDIS_URL: "redis://services-stack_postiz-redis:6379"
      TEMPORAL_ADDRESS: "services-stack_temporal:7233"

      BACKEND_INTERNAL_URL: "http://localhost:3000"
      IS_GENERAL: "true"
      DISABLE_REGISTRATION: "false"
      RUN_CRON: "true"

      STORAGE_PROVIDER: "local"
      UPLOAD_DIRECTORY: "/uploads"
      NEXT_PUBLIC_UPLOAD_DIRECTORY: "/uploads"
    volumes:
      - postiz-config:/config/
      - postiz-uploads:/uploads/
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.postiz.rule=Host(`postiz.vps.andrejvysny.sk`)"
        - "traefik.http.routers.postiz.entrypoints=websecure"
        - "traefik.http.routers.postiz.tls=true"
        - "traefik.http.routers.postiz.tls.certresolver=letsencrypt"
        - "traefik.http.services.postiz.loadbalancer.server.port=5000"

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    networks:
      - vps-public
      - db-internal
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: services-stack_postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: "${N8N_DB_PASSWORD}"

      N8N_HOST: n8n.vps.andrejvysny.sk
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      WEBHOOK_URL: https://n8n.vps.andrejvysny.sk/

      NODE_ENV: production
      GENERIC_TIMEZONE: Europe/Bratislava
      N8N_ENCRYPTION_KEY: "${N8N_ENCRYPTION_KEY}"
    volumes:
      - n8n-data:/home/node/.n8n
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.n8n.rule=Host(`n8n.vps.andrejvysny.sk`)"
        - "traefik.http.routers.n8n.entrypoints=websecure"
        - "traefik.http.routers.n8n.tls=true"
        - "traefik.http.routers.n8n.tls.certresolver=letsencrypt"
        - "traefik.http.services.n8n.loadbalancer.server.port=5678"

networks:
  vps-public:
    external: true
  db-internal:
    driver: overlay
  postiz-internal:
    driver: overlay
  temporal-internal:
    driver: overlay

configs:
  pg-init-v2:
    file: ./pg-init.sql

volumes:
  traefik-certificates:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/traefik-certificates

  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/postgres/pg

  n8n-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/n8n/files

  postiz-redis-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/postiz/redis

  postiz-uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/postiz/uploads

  postiz-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/postiz/config

  temporal-es-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/temporal/es
